#Part 2: First in first out (FIFO)
array1 = []
print("Push: ")
array1.append("A")
print(array1)
array1.append("B")
print(array1)
array1.append("C")
print(array1)
array1.append("D")
print(array1)
array1.append("E")
print(array1)
array1.append("F")
print(array1)

print("Pop(0): ")
array1.pop(0)
print(array1)
array1.pop(0)
print(array1)
array1.pop(0)
print(array1)
array1.pop(0)
print(array1)
array1.pop(0)
print(array1)
array1.pop(0)
print(array1)

